### ISSUE TITLE
switch to sbt-paradox-material-theme?

### ISSUE THREAD

**Issue by pjfanning** [apache/incubator-pekko-sbt-paradox#103]
https://github.com/sbt/sbt-paradox-material-theme/releases/tag/v0.7.0

**Comment by mdedetrich** [comment]
This is already done, see https://github.com/apache/incubator-pekko-sbt-paradox/pull/92?

Or do you mean propagate it to Pekko projects?

**Comment by pjfanning** [comment]
> This is already done, see #92?
> 
> Or do you mean propagate it to Pekko projects?

the plugins.sbt was reverted in https://github.com/mdedetrich/incubator-pekko-sbt-paradox/commit/31845fdde373f3210aa7ca8bcbfb6f660f430bb8#diff-8fd74420ca55aa91d4c53775d2a55a999c405b5a4fafeaf73b7f0ef83e1f3b0c

**Comment by mdedetrich** [comment]
sbt-paradox-material-theme is not the same as sbt-paradox, I still don't understand what the issue is? We are currently right now using sbt-paradox-material-theme 0.7.0.

Or is your main concern that we are not using the latest version of sbt-paradox/sbt-paradox-theme?

**Comment by pjfanning** [comment]
Ok - I'll close this
