### ISSUE TITLE
make incubator part of the footer.st optional (a parameter)

### ISSUE THREAD

**Issue by pjfanning** [apache/incubator-pekko-sbt-paradox#115]
https://github.com/apache/incubator-pekko-sbt-paradox/blob/023c449e7b136af695f2240627daff5a05b3f038/theme/src/main/assets/partials/footer.st#L64-L73

When we become a TLP, we will want just the copyright part of the footer.

wdyt @mdedetrich ? - is this something we can put in the 1.0.1 release of this module?

**Comment by mdedetrich** [comment]
Let me have a look at it, if it takes too long to implement I would recommend just removing it in 1.0.2

**Comment by mdedetrich** [comment]
PR up at https://github.com/apache/incubator-pekko-sbt-paradox/pull/116
