### ISSUE TITLE
need to add LICENSE and related files to jars

### ISSUE THREAD

**Issue by pjfanning** [apache/incubator-pekko-sbt-paradox#23]
* copy LICENSE from git to jar META-INF/LICENSE
* also NOTICE and DISCLAIMER

**Comment by pjfanning** [comment]
This is done

**Comment by mdedetrich** [comment]
@pjfanning I am pretty sure this is already done, the sbt-apache-paradox plugin handles this and it has already been integrated into the project, see https://github.com/apache/incubator-pekko-sbt-paradox/pull/27 (or am I missing something)?

**Comment by pjfanning** [comment]
The issue was already open and I'm just trying to link them to the PRs.
