### ISSUE TITLE
Add menu to template that provides links to Apache pages

### ISSUE THREAD

**Issue by jrudolph** [apache/incubator-pekko-sbt-paradox#24]
(courtesy of @pjfanning from https://github.com/apache/incubator-pekko/issues/92#issuecomment-1407728069):

  * Apache home page 
  * Sponsoring
  * License
  * Trademark
  * Security
  * Thanks
  * Upcoming Apache Event (a gif - or a link to a page) 
  * see the 'Apache Software Foundation' menu at top right of https://spark.apache.org/

**Comment by pjfanning** [comment]
@jrudolph I'm closing this as we have a solution. Please reopen if you think more work is needed.
