### ISSUE TITLE
Fork paradox-material-theme?

### ISSUE THREAD

**Issue by mdedetrich** [apache/incubator-pekko-sbt-paradox#34]
As noted in https://github.com/apache/incubator-pekko-grpc/pull/36#issuecomment-1448137032, due to the usage of paradox-material-theme we are dealing with binary compatibility problems stemming from the fact that paradox-material-theme appears to be unmaintained for years and hence is built against an ancient version of circe.

I think the fastest solution to solve this problem for now is to fork the project, apply the changes in https://github.com/jonas/paradox-material-theme/pull/34 and just republish it another a different org.

**Comment by mdedetrich** [comment]
> Maybe we can work around the circe issue but in general forking is not super appealing

I already tried with no avail, we are dealing with a 6 year old version of Circe vs one that is quite recent

> If we do it, we might just want to do it right here.

I was thinking of forking it into my own org (mdedetrich) just to unblock us, I don't see it taking more than a few hours (have done it before).

We can then look into a more appropriate solution later on

**Comment by samueleresca** [comment]
An alternative to fork might be to pull the styling files and paradox templates from [paradox-material-theme](https://github.com/jonas/paradox-material-theme) into this repo. It would simplify the way we style our docs by reducing the layers from 3 (`docs-> pekko-sbt-paradox -> paradox-material-theme`)  to 2 (`docs -> pekko-sbt-paradox`).

**Comment by pjfanning** [comment]
For me, the real issue is #84. The requirement to 'release' UI changes and then go through all our repos and even multiple branches on repos and uptake the changes - that is a massive overhead for small UI changes.

**Comment by mkurz** [comment]
@mdedetrich I think this issue can now be closed, given that you/we can maintain https://github.com/sbt/sbt-paradox-material-theme now and a new release is coming soon.
