### ISSUE TITLE
change 'Donate' label for sponsorship link

### ISSUE THREAD

**Issue by pjfanning** [apache/incubator-pekko-sbt-paradox#45]
I presume that the 'Donate' label was used to save space and improve rendering.

It is more standard to use the 'Sponsorship' as the label. 'Sponsor' would be a possible alternative.

One option would be to try to get all the ASF links to render as one per line, so that we wouldn't have to worry about the label length as much.

**Comment by jrudolph** [comment]
I just used what Flink uses :)

**Comment by jrudolph** [comment]
![image](https://user-images.githubusercontent.com/9868/223973947-b10de552-7c79-4541-837a-1d4c40bf66de.png)

**Comment by pjfanning** [comment]
seems ok as is
