### ISSUE TITLE
pekkoParadoxCopyright property should respect new lines

### ISSUE THREAD

**Issue by pjfanning** [apache/incubator-pekko-sbt-paradox#48]
We need to be able to space the copyright statement over multiple lines.

    pekkoParadoxCopyright :=
      """© 2011-2022 <a href="https://www.lightbend.com">Lightbend, Inc</a>.
        |Apache Pekko, Pekko, and its feather logo are trademarks of The Apache Software Foundation.""".stripMargin

These 2 lines should appear on 2 separate lines instead of appearing on same line in the generated HTML.

**Comment by jrudolph** [comment]
This is HTML, so you can use `</br>` for newlines where needed.
