### ISSUE TITLE
Revert spray-json workaround

### ISSUE THREAD

**Issue by mdedetrich** [apache/incubator-pekko-sbt-paradox#91]
Now that sbt-paradox-material-theme has been [forked](https://github.com/apache/incubator-pekko-sbt-paradox/issues/34#issuecomment-1941571636) and will soon be released we can revert this workaround https://github.com/apache/incubator-pekko-sbt-paradox/pull/35

**Comment by mdedetrich** [comment]
@Roiocam I think you were also looking in this area, this may not even be relevant

**Comment by mdedetrich** [comment]
Solved in https://github.com/apache/incubator-pekko-sbt-paradox/pull/98

**Comment by Roiocam** [comment]
It is not related to https://github.com/apache/incubator-pekko/issues/1097, but I still appreciate these context inputs. Thank you.
